# Generated by Django 5.1 on 2024-08-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptransaction',
            name='destination_number',
        ),
        migrations.AddField(
            model_name='otptransaction',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
